---

# Set postgresql state when configuration changes are made. Recommended values:
# `restarted` or `reloaded`
postgresql_cluster_restarted_state: "restarted"

postgresql_cluster_user: postgres
postgresql_cluster_group: postgres

postgresql_cluster_unix_socket_directories:
  - /var/run/postgresql

# Global configuration options that will be set in postgresql.conf.
postgresql_cluster_global_config_options:
  - option: unix_socket_directories
    value: '{{ postgresql_cluster_unix_socket_directories | join(",") }}'