---
- include_role:
    name: postgres-cluster-hba-config
  when: not (postgresql_cluster_is_monitor | default('False') | bool)

- include_role:
    name: postgres-cluster-configure
  when: not (postgresql_cluster_is_monitor | default('False') | bool)