
---

- name: Check if PostgreSQL database is initialized.
  stat:
    path: "{{ postgresql_data_dir }}/PG_VERSION"
  register: pgdata_dir_version


- include_tasks: existing_node.yml
  when: (pgdata_dir_version.stat.exists) and not (postgresql_cluster_is_monitor | default('False') | bool)
