- hosts: all
  become: true
  gather_facts: False
  tasks:
    # ansible only requires only a minimal installation of python 2.x on the managed machines
    - name: "ansible required: install python"
      raw: apt update -y && apt install python-minimal -y && apt install python-simplejson -y

- hosts: all
  become: true
  tasks:
    - name: "set up bashrc for root user"
      copy:
        src: "{{ playbook_dir }}/roles/user-setup/files/.bashrc"
        dest: "/root/.bashrc"
        owner: "0"
        group: "0"
        mode: 0600
        
- hosts: all
  become: true
  tasks:
    - name: Ensure the en_US locale exists
      locale_gen:
        name: en_US.UTF-8
        state: present
    - name: set en_US as default locale
      command: update-locale set-locale LANG=en_US.UTF-8 LC_ALL=en_US.UTF-8

- hosts: all
  become: true
  vars:   
    apt_update_cache: True
    apt_restart_after_dist_upgrade: True
  roles:
    - role: essential-software-setup
