---

# this assumes that the main playbook has alredy been run and is only intended as an upgrade playbook

- hosts: postgres_cluster
  any_errors_fatal: true
  become: true
  roles:
    - name: postgres-cluster-load-vars
    - role: postgres-cluster-hba-config
    - role: postgres-cluster-pgbouncer-setup
      when: postgresql_cluster_pg_bouncer_include | default('False') | bool
    - role: postgres-cluster-pgbouncer-client-setup
      when: postgresql_cluster_pg_bouncer_include | default('False') | bool
