---

- hosts: postgres_cluster
  any_errors_fatal: true
  become: true
  roles:
    - name: postgres-cluster-load-vars
    - role: postgres-cluster-users
    - role: postgres-cluster-groups
    - role: postgres-cluster-databases
    - role: postgres-cluster-hba-config
    - role: postgres-cluster-pgbouncer-client-setup
      when: postgresql_cluster_pg_bouncer_include | default('False') | bool
