---

- hosts: postgres_cluster
  become: true
  roles:
    - name: postgres-cluster-load-vars
    - role: postgres-cluster-users
    - role: postgres-cluster-databases
    - role: postgres-cluster-hba-config
