---
- hosts: postgres_cluster
  become: true
  vars:
    setup_additional_groups:
      - name: "postgres"
        requires_root_password: True
    setup_additional_users:
      - name: "postgres"
        group: "postgres"
        system: True
        is_sudo: False
    ssl_cert_dirs:
      - directory: "postgres_server"
        owner: "postgres"
        group: "postgres"
  roles:
    - role: user-setup
    - role: force-reconnect
    - role: copy-ssl-certs

- hosts: postgres_cluster
  become: true
  roles:
    - name: postgres-cluster-load-vars
    - role: postgres-pre-setup
    - role: postgres-cluster-install
    - role: postgres-cluster-user-setup
    - role: postgres-cluster-pg-auto-failover-install
    - role: postgres-cluster-monitor-initialize
    # update all pg_hba configs for all already initialized nodes
    - role: postgres-cluster-data-initialize-existing


- hosts: postgres_cluster
  become: true
  serial: true
  roles:
    - name: postgres-cluster-load-vars
    # one by one add all new data nodes
    - role: postgres-cluster-data-initialize-new

- hosts: postgres_cluster
  become: true
  roles:
    - name: postgres-cluster-load-vars
    - role: postgres-cluster-users
    - role: postgres-cluster-databases
