# pg_auto_failover_ansible

# Copyright (C) 2020  NeuroForge GmbH & Co.KG <https://neuroforge.de/>

# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU Affero General Public License as published
# by the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.

# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU Affero General Public License for more details.

# You should have received a copy of the GNU Affero General Public License
# along with this program.  If not, see <https://www.gnu.org/licenses/>.
---
- name: "compute monitor_nodes_list"
  vars:
    monitor_node_ip : "{{ hostvars[item]['host_ip'] | default(hostvars[item]['ansible_host']) }}"
  set_fact:
    postgresql_monitor_node_ips: "{{ (postgresql_monitor_node_ips | default([])) + [monitor_node_ip] }}"
  with_items: "{{ groups['postgres_cluster'] | default([]) }}"


# TODO: add support for crl files
# FIXME: monitor port may be wrong if its overridden on a per host basis !!!

# --group {{ postgresql_cluster_group | default('0') }} \
- name: "run pg_autoctl create postgres"
  become_user: "{{ postgresql_user }}"
  vars:
    first_monitor_node: "{{ postgresql_monitor_node_ips | first }}"
  shell: >
    PATH="$PATH:{{ postgresql_bin_path }}" pg_autoctl create postgres \
    --pgdata "{{ postgresql_data_dir }}" \
    --skip-pg-hba \
    --formation {{ postgresql_cluster_formation | default('default') }} \
    --ssl-ca-file "{{ postgresql_cluster_ssl_ca_file | default('/data/ansible/certs/postgres_server/rootCA.crt') }}" \
    --server-key "{{ postgresql_cluster_server_key | default('/data/ansible/certs/postgres_server/server.key') }}" \
    --server-cert "{{ postgresql_cluster_server_cert | default('/data/ansible/certs/postgres_server/server.crt') }}" \
    --nodename "{{ host_ip }}" \
    --pgport "{{ postgresql_cluster_port | default('5433') }}" \
    --monitor postgres://autoctl_node@{{ first_monitor_node }}:{{ postgresql_cluster_port | default('5433') }}/pg_auto_failover
  when: not (postgresql_cluster_is_monitor | default('False') | bool)

- name: "create systemd config for cluster"
  shell: >
    PATH="$PATH:{{ postgresql_bin_path }}" pg_autoctl -q show systemd \
    --pgdata "{{ postgresql_data_dir }}" | tee /etc/systemd/system/{{ postgresql_daemon }}.service
  when: not (postgresql_cluster_is_monitor | default('False') | bool)

- name: "make sure database cluster service is started and enabled at boot"
  systemd:
    state: started
    enabled: true
    daemon_reload: yes
    name: "{{ postgresql_daemon }}"
  when: not (postgresql_cluster_is_monitor | default('False') | bool)

- include_role:
    name: postgres-cluster-hba-config
  when: not (postgresql_cluster_is_monitor | default('False') | bool)

- include_role:
    name: postgres-cluster-configure
  when: not (postgresql_cluster_is_monitor | default('False') | bool)