---
- name: "pin postgres packages"
  template:
    src: "pgdg.preferences.j2"
    dest: "/etc/apt/preferences.d/pgdg"
    owner: root
    group: root

- name: Ensure PostgreSQL Python libraries are installed.
  apt:
    name: "{{ postgresql_cluster_python_library }}"
    state: present
  when: postgresql_cluster_python_library is defined

- name: Ensure PostgreSQL Python libraries are installed via pip
  pip:
    name: "{{ postgresql_cluster_python_pip_library }}"
    state: present
  when: postgresql_cluster_python_pip_library is defined

- name: Ensure PostgreSQL packages are installed.
  apt:
    name: "{{ postgresql_cluster_packages }}"
    state: present

- name: Ensure all configured locales are present.
  locale_gen: "name={{ item }} state=present"
  with_items: "{{ postgresql_cluster_locales }}"
  register: locale_gen_result