---
__postgresql_cluster_name: "main_cluster"
__postgresql_cluster_port: "5433"
__postgresql_cluster_version: "12"
__postgresql_cluster_data_dir: "/var/lib/postgresql/{{ postgresql_cluster_version | default(__postgresql_cluster_version) }}/{{ postgresql_cluster_name | default(__postgresql_cluster_name) }}"
__postgresql_cluster_bin_path: "/usr/lib/postgresql/{{ postgresql_cluster_version | default(__postgresql_cluster_version) }}/bin"
__postgresql_cluster_config_path: "/var/lib/postgresql/{{ postgresql_cluster_version | default(__postgresql_cluster_version) }}/{{ postgresql_cluster_name | default(__postgresql_cluster_name) }}"
__postgresql_cluster_daemon: "postgresql_{{ postgresql_cluster_name | default(__postgresql_cluster_name) }}"
__postgresql_cluster_packages:
  - postgresql
  - postgresql-contrib
  - libpq-dev
postgresql_cluster_python_library: python3-psycopg2
