---
- name: "ensure /data/ansible/pg_dump exists"
  file:
    path: /data/ansible/pg_dump
    state: directory
    owner: "root"
    group: "root"
    # pg_dump apparently wants to cd back to the directory
    mode: 0711

- name: "ensure /data/ansible/pg_dumps exists"
  file:
    path: /data/ansible/pg_dumps
    state: directory
    owner: "postgres"
    group: "postgres"
    mode: 0700

- name: copy dump_all.sh script
  template:
    src: dump_all.sh.j2
    dest: /data/ansible/pg_dump/dump_all.sh
    owner: "root"
    group: "root"
    mode: 0700

- name: copy start_dump.sh script
  copy:
    src: start_dump.sh
    dest: /data/ansible/pg_dump/start_dump.sh
    owner: "root"
    group: "root"
    mode: 0700
    
- name: Create cronjob for postgres dump
  when: "postgres_backup_enabled | default(True) | bool"
  cron:
    name: "start automatic postgres dump"
    user: "root"
    minute: "0"
    hour: "2"
    job: "bash /data/ansible/pg_dump/start_dump.sh"