---
# Variable configuration.
- name: Include OS-specific variables (Debian).
  include_vars: "{{ ansible_distribution }}-{{ ansible_distribution_version.split('.')[0] }}.yml"
  when: ansible_os_family == 'Debian'

- name: Define postgresql_packages.
  set_fact:
    postgresql_cluster_packages: "{{ __postgresql_packages | list }}"
  when: postgresql_packages is not defined

- name: Define postgresql_version.
  set_fact:
    postgresql_cluster_version: "{{ __postgresql_version }}"
  when: postgresql_version is not defined

- name: Define postgresql_cluster_daemon.
  set_fact:
    postgresql_cluster_daemon: "{{ __postgresql_cluster_daemon }}"
  when: postgresql_cluster_daemon is not defined

- name: Define postgresql_cluster_data_dir.
  set_fact:
    postgresql_cluster_data_dir: "{{ __postgresql_cluster_data_dir }}"
  when: postgresql_cluster_data_dir is not defined

- name: Define postgresql_cluster_port.
  set_fact:
    postgresql_cluster_port: "{{ __postgresql_cluster_port }}"
  when: postgresql_cluster_port is not defined

- name: Define postgresql_cluster_bin_path.
  set_fact:
    postgresql_cluster_bin_path: "{{ __postgresql_cluster_bin_path }}"
  when: postgresql_cluster_bin_path is not defined

- name: Define postgresql_cluster_config_path.
  set_fact:
    postgresql_cluster_config_path: "{{ __postgresql_cluster_config_path }}"
  when: postgresql_cluster_config_path is not defined

- name: Define postgresql_cluster_unix_socket_directories_mode.
  set_fact:
    postgresql_cluster_unix_socket_directories_mode: >-
      {{ __postgresql_cluster_unix_socket_directories_mode | default('02775') }}
  when: postgresql_cluster_unix_socket_directories_mode is not defined
