---

- name: Check if PostgreSQL database is initialized.
  stat:
    path: "{{ postgresql_cluster_data_dir }}/PG_VERSION"
  register: pgdata_dir_version

- name: "copy deb.sh to /tmp/pg_auto_failover_deb.sh"
  copy:
    src: "deb.sh"
    dest: "/tmp/pg_auto_failover_deb.sh"
    owner: root
    group: root
    mode: 0700
  when: not pgdata_dir_version.stat.exists

- name: "run /tmp/pg_auto_failover_deb.sh"
  command: "bash /tmp/pg_auto_failover_deb.sh"
  when: not pgdata_dir_version.stat.exists

- name: "install postgresql-12-auto-failover-1.4"
  apt: 
    name: postgresql-12-auto-failover-1.4
    state: present
    update_cache: "{{ apt_update_cache | default('True') }}"
  when: not pgdata_dir_version.stat.exists